Repository Kakaobootcamp-HackerTon/jerryToy-fe, pull requests merged in 2024-08, with the labels that each got.

#1 chore: 프로젝트 초기설정
  .babelrc
  .eslintrc.js
  .gitignore
  .prettierrc.js
  README.md
  README.old.md
  babel.config.js
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: chore

#2 feat: left drawer 생성
  package.json
  src/App.tsx
  src/components/drawer/index.tsx
  src/components/drawer/styles.tsx
  src/components/list/index.tsx
  src/components/list/styles.tsx
  yarn.lock
Labels: feat

#3 Feat: connect kakao-map-api
  .gitignore
  index.html
  src/App.tsx
  src/pages/index.tsx
Labels: feat

#5 Jamie/add router
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/index.css
  src/index.tsx
  src/styles/globalStyles.tsx
Labels: feat, remove

#6 Jamie/merge map drawer
  src/components/drawer/index.tsx
  src/components/drawer/styles.tsx
  src/pages/index.tsx
Labels: feat

#8 Feat: login 페이지 추가
  package.json
  src/Router.tsx
  src/assets/cover.png
  src/components/authInput/index.tsx
  src/components/authInput/styles.tsx
  src/components/lineText/index.tsx
  src/components/lineText/styles.tsx
  src/components/submitBtn/index.tsx
  src/components/submitBtn/styles.tsx
  src/components/textInput/index.tsx
  src/components/title/styles.tsx
  src/pages/login/index.tsx
  src/pages/login/styles.tsx
  src/styles/globalStyles.tsx
  yarn.lock
Labels: feat

#9 feat: 회원가입 로직 추가
  package.json
  src/Router.tsx
  src/assets/congratulations_image.png
  src/components/signUp/accountSetup.tsx
  src/components/signUp/ageSelection.tsx
  src/components/signUp/genderSelection.tsx
  src/components/signUp/mbtiSelection.tsx
  src/components/signUp/nicknameSetting.tsx
  src/components/signUp/styles.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/styles.tsx
  src/pages/signUpDone/index.tsx
  src/pages/signUpDone/styles.tsx
  yarn.lock
Labels: feat

#15 feat : 회원가입 api 연결
  package.json
  src/Router.tsx
  src/pages/signUp/index.tsx
  src/pages/signUpDone/index.tsx
  src/pages/signUpDone/styles.tsx
  yarn.lock
Labels: feat

#18 feat: userinfo 페이지 완성
  src/Router.tsx
  src/assets/background.jpg
  src/components/userInfo/index.tsx
  src/components/userInfo/styles.tsx
  src/pages/user/index.tsx
  src/pages/user/styles.tsx
Labels: feat

#21 feat: post , makepost 기능생성
  src/Router.tsx
  src/components/post/index.tsx
  src/components/post/styles.tsx
  src/components/post/transferList.tsx
  src/components/post/types.ts
  src/pages/makePost/index.tsx
  src/pages/post/index.tsx
  src/types/index.tsx
Labels: feat
